version: '3.4'

services:
  quicken.datefixer.minapi:
    image: ${DOCKER_REGISTRY-}quickendatefixerminapi
    build:
      context: .
      dockerfile: Quicken.DateFixer.MinApi/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
